test changes made
FootprintAI/git-tutorials pull request #1
Opened 2024-10-22 03:46 UTC by 1lyvianis

edited a few rows

2024-10-22 03:49 UTC, hsinatfootprintai commented on README.md
> +changes!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
why do you add this?

2024-10-22 03:50 UTC, hsinatfootprintai requested changes
please fix it to be meaningful

2024-10-29 03:24 UTC, 1lyvianis commented
> please fix it to be meaningful

discarded previous codes to comply with the latest version

2024-10-29 03:56 UTC, 1lyvianis commented on README.md
> +changes!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
done

2024-10-29 03:57 UTC, hsinatfootprintai approved these changes

2024-10-29 03:57 UTC, merged